### ISSUE TITLE
Upgrade Astro, maybe other dependencies

### ISSUE THREAD

**Issue by broadwell** [sul-cidr/pianolatron#128]
Just making this an official request. Do you reckon it's worth upgrading to Svelte 4 as well?

Of the other dependencies, I think that only the updates to Openseadragon might be impactful. I'll take a look at those myself.

**Comment by broadwell** [comment]
Update: the OSD upgrade is relatively painless and may be helpful; I made a separate PR for it: https://github.com/sul-cidr/pianolatron/pull/129

**Comment by simonwiles** [comment]
Closed by #130.
