### ISSUE TITLE
Create a separate "listen" mode for the app

### ISSUE THREAD

**Issue by broadwell** [sul-cidr/pianolatron#134]
- As suggested in the wireframes, the "listen" mode likely will be extremely stripped down compared to the feature-rich "perform" view/mode, with no volume or tempo adjustments available. Basically it will just have the app header, the roll metadata display, the roll image viewer (which we may also provide the option of turning off) with the default visualization settings applied and its accompanying navigator image strip, a movable progress slider, and eventually a button for sharing a bookmark of the roll. 
- People are probably more likely to share links to this view rather than to the "perform" view, so giving it the shortest possible URL path is preferable.
- This view also probably won't have a roll selector component on it at all; instead it will have a link to the search/browse page in the header (which probably will be derived from the template developed for the static pages).
- Due to the above, this view will only be reached via a link to play a specific roll, so depending on the routing options available from Svelte/Astro, the URLs could look like https://pianolatron.stanford.edu/[DRUID]/ or else just https://pianolatron.stanford.edu/?roll=[DRUID]
- So the current feature-rich view would become the "perform" view, and would be reached via its own URL and/or the URL with a specified DRUID, something like https://pianolatron.stanford.edu/perform/<?druid=[DRUID]>

**Comment by cfitz** [comment]
https://github.com/sul-cidr/pianolatron/pull/137/files
