### ISSUE TITLE
Consider integrating Simon's "legend" panel

### ISSUE THREAD

**Issue by broadwell** [sul-cidr/pianolatron#157]
The idea is to try to integrate as many of the new features from the PR https://github.com/sul-cidr/pianolatron/pull/86 as we can.

At the least, we should display the instantaneous roll velocity (in ft/min^2) in the perform view. Showing a legend for the hole colors and color ranges in the perform view is also a nice-to-have.

The legend code is already pretty functional, but may need a final once-over, and as it's fairly old, some parts may need to be updated to match up with how the app currently works.

**Comment by cfitz** [comment]
First pass at https://github.com/sul-cidr/pianolatron/pull/190

**Comment by broadwell** [comment]
After further consideration, I'd propose the following refinements:
- The legend doesn't appear in the current position (bottom left of roll) at all, and instead is broken into two components that are only displayed in the Perform mode.
- The **Feet per minute** and **Time index data** can be displayed in the default right-hand panel (the one with Volume: at the top), probably between the Progress: slider and the buttons. The **At current tempo** readout can be removed because it's redundant with the Tempo slider. Also, the values should read 0 rather than NaN when no information is available.
- The hole color legend sub-component probably should just be moved to the Settings (gear icon) right-hand panel (the one that begins with Visualization Settings), maybe between the Visualization Settings and Roll Emulation Settings control blocks.
