### ISSUE TITLE
Change default Volume multiplier value from 1.5 to 1

### ISSUE THREAD

**Issue by broadwell** [sul-cidr/pianolatron#171]
This is something that has been discussed for a long time. There's some concern that the app as a whole is too quiet by default when the Volume setting is 1, but the best solution in that case is for the user to increase their system volume, not to artificially increase the force with which the virtual piano hammers hit the virtual strings.

**Comment by cfitz** [comment]
I think PR #180 does this? Just changes the volumeCoefficient from 1.5 to 1? 
The delta is still .1, like the other volume knobs.
