### ISSUE TITLE
"Mark Start" and "Mark End" buttons should be toggle-able

### ISSUE THREAD

**Issue by broadwell** [sul-cidr/pianolatron#173]
Ideally, each button icon would be styled active (white) when it has been used to set a start or stop point. Clicking the button again would remove that start or stop point (and remove the line from the viz) and change the button style back to the default gray.

A couple of related requests:
- The tooltip of the "Mark End" button currently reads "Mark Start" - would be great to fix this.
- Can we allow the user to mark 0% as the start point? This is entirely redundant because 0% is the start point when no start point is selected, but still, the user might be confused about why they can't set a start point at 0%.

**Comment by cfitz** [comment]
I put in something in  #178

**Comment by cfitz** [comment]
Additional fixes in https://github.com/sul-cidr/pianolatron/pull/183
