### ISSUE TITLE
Quick fix (probably): Bookmarks created when start and end markers are active have the same start and end percentage

### ISSUE THREAD

**Issue by broadwell** [sul-cidr/pianolatron#191]
E.g., the bookmark that is copied to the clipboard looks like this:
https://pianolatron-develop.netlify.app/?druid=cw378sb0125&start=15.03&end=15.03
When it should look like this:
https://pianolatron-develop.netlify.app/?druid=cw378sb0125&start=15.03&end=20.32

**Comment by cfitz** [comment]
🤦 fixed
